/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.records;


import com.xnelo.filearch.jooq.tables.Artifacts;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ArtifactsRecord extends UpdatableRecordImpl<ArtifactsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>FILEARCH.artifacts.id</code>.
     */
    public ArtifactsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.artifacts.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>FILEARCH.artifacts.owner_user_id</code>.
     */
    public ArtifactsRecord setOwnerUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.artifacts.owner_user_id</code>.
     */
    public Long getOwnerUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>FILEARCH.artifacts.stored_files_id</code>.
     */
    public ArtifactsRecord setStoredFilesId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.artifacts.stored_files_id</code>.
     */
    public Long getStoredFilesId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>FILEARCH.artifacts.storage_key</code>.
     */
    public ArtifactsRecord setStorageKey(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.artifacts.storage_key</code>.
     */
    public String getStorageKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>FILEARCH.artifacts.mime_type</code>.
     */
    public ArtifactsRecord setMimeType(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.artifacts.mime_type</code>.
     */
    public String getMimeType() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArtifactsRecord
     */
    public ArtifactsRecord() {
        super(Artifacts.ARTIFACTS);
    }

    /**
     * Create a detached, initialised ArtifactsRecord
     */
    public ArtifactsRecord(Long id, Long ownerUserId, Long storedFilesId, String storageKey, String mimeType) {
        super(Artifacts.ARTIFACTS);

        setId(id);
        setOwnerUserId(ownerUserId);
        setStoredFilesId(storedFilesId);
        setStorageKey(storageKey);
        setMimeType(mimeType);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ArtifactsRecord
     */
    public ArtifactsRecord(com.xnelo.filearch.jooq.tables.pojos.Artifacts value) {
        super(Artifacts.ARTIFACTS);

        if (value != null) {
            setId(value.getId());
            setOwnerUserId(value.getOwnerUserId());
            setStoredFilesId(value.getStoredFilesId());
            setStorageKey(value.getStorageKey());
            setMimeType(value.getMimeType());
            resetTouchedOnNotNull();
        }
    }
}
