/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.records;


import com.xnelo.filearch.jooq.tables.FileTags;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FileTagsRecord extends TableRecordImpl<FileTagsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>FILEARCH.file_tags.file_id</code>.
     */
    public FileTagsRecord setFileId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.file_tags.file_id</code>.
     */
    public Long getFileId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>FILEARCH.file_tags.tag_id</code>.
     */
    public FileTagsRecord setTagId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.file_tags.tag_id</code>.
     */
    public Long getTagId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileTagsRecord
     */
    public FileTagsRecord() {
        super(FileTags.FILE_TAGS);
    }

    /**
     * Create a detached, initialised FileTagsRecord
     */
    public FileTagsRecord(Long fileId, Long tagId) {
        super(FileTags.FILE_TAGS);

        setFileId(fileId);
        setTagId(tagId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised FileTagsRecord
     */
    public FileTagsRecord(com.xnelo.filearch.jooq.tables.pojos.FileTags value) {
        super(FileTags.FILE_TAGS);

        if (value != null) {
            setFileId(value.getFileId());
            setTagId(value.getTagId());
            resetTouchedOnNotNull();
        }
    }
}
