/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.records;


import com.xnelo.filearch.jooq.tables.GroupAuditLog;

import java.time.OffsetDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupAuditLogRecord extends UpdatableRecordImpl<GroupAuditLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>FILEARCH.group_audit_log.id</code>.
     */
    public GroupAuditLogRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_audit_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>FILEARCH.group_audit_log.group_id</code>.
     */
    public GroupAuditLogRecord setGroupId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_audit_log.group_id</code>.
     */
    public Long getGroupId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>FILEARCH.group_audit_log.user_id</code>.
     */
    public GroupAuditLogRecord setUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_audit_log.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>FILEARCH.group_audit_log.modified_at</code>.
     */
    public GroupAuditLogRecord setModifiedAt(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_audit_log.modified_at</code>.
     */
    public OffsetDateTime getModifiedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>FILEARCH.group_audit_log.modification</code>.
     */
    public GroupAuditLogRecord setModification(Short value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_audit_log.modification</code>.
     */
    public Short getModification() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>FILEARCH.group_audit_log.pre_op_data</code>.
     */
    public GroupAuditLogRecord setPreOpData(JSONB value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_audit_log.pre_op_data</code>.
     */
    public JSONB getPreOpData() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>FILEARCH.group_audit_log.post_op_data</code>.
     */
    public GroupAuditLogRecord setPostOpData(JSONB value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_audit_log.post_op_data</code>.
     */
    public JSONB getPostOpData() {
        return (JSONB) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupAuditLogRecord
     */
    public GroupAuditLogRecord() {
        super(GroupAuditLog.GROUP_AUDIT_LOG);
    }

    /**
     * Create a detached, initialised GroupAuditLogRecord
     */
    public GroupAuditLogRecord(Long id, Long groupId, Long userId, OffsetDateTime modifiedAt, Short modification, JSONB preOpData, JSONB postOpData) {
        super(GroupAuditLog.GROUP_AUDIT_LOG);

        setId(id);
        setGroupId(groupId);
        setUserId(userId);
        setModifiedAt(modifiedAt);
        setModification(modification);
        setPreOpData(preOpData);
        setPostOpData(postOpData);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised GroupAuditLogRecord
     */
    public GroupAuditLogRecord(com.xnelo.filearch.jooq.tables.pojos.GroupAuditLog value) {
        super(GroupAuditLog.GROUP_AUDIT_LOG);

        if (value != null) {
            setId(value.getId());
            setGroupId(value.getGroupId());
            setUserId(value.getUserId());
            setModifiedAt(value.getModifiedAt());
            setModification(value.getModification());
            setPreOpData(value.getPreOpData());
            setPostOpData(value.getPostOpData());
            resetTouchedOnNotNull();
        }
    }
}
