/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.records;


import com.xnelo.filearch.jooq.tables.GroupMembers;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupMembersRecord extends TableRecordImpl<GroupMembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>FILEARCH.group_members.user_id</code>.
     */
    public GroupMembersRecord setUserId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_members.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>FILEARCH.group_members.group_id</code>.
     */
    public GroupMembersRecord setGroupId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_members.group_id</code>.
     */
    public Long getGroupId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>FILEARCH.group_members.accepted</code>.
     */
    public GroupMembersRecord setAccepted(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_members.accepted</code>.
     */
    public Boolean getAccepted() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupMembersRecord
     */
    public GroupMembersRecord() {
        super(GroupMembers.GROUP_MEMBERS);
    }

    /**
     * Create a detached, initialised GroupMembersRecord
     */
    public GroupMembersRecord(Long userId, Long groupId, Boolean accepted) {
        super(GroupMembers.GROUP_MEMBERS);

        setUserId(userId);
        setGroupId(groupId);
        setAccepted(accepted);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised GroupMembersRecord
     */
    public GroupMembersRecord(com.xnelo.filearch.jooq.tables.pojos.GroupMembers value) {
        super(GroupMembers.GROUP_MEMBERS);

        if (value != null) {
            setUserId(value.getUserId());
            setGroupId(value.getGroupId());
            setAccepted(value.getAccepted());
            resetTouchedOnNotNull();
        }
    }
}
