/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.records;


import com.xnelo.filearch.jooq.tables.Groups;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupsRecord extends UpdatableRecordImpl<GroupsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>FILEARCH.groups.id</code>.
     */
    public GroupsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.groups.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>FILEARCH.groups.owner_user_id</code>.
     */
    public GroupsRecord setOwnerUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.groups.owner_user_id</code>.
     */
    public Long getOwnerUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>FILEARCH.groups.group_name</code>.
     */
    public GroupsRecord setGroupName(byte[] value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.groups.group_name</code>.
     */
    public byte[] getGroupName() {
        return (byte[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupsRecord
     */
    public GroupsRecord() {
        super(Groups.GROUPS);
    }

    /**
     * Create a detached, initialised GroupsRecord
     */
    public GroupsRecord(Long id, Long ownerUserId, byte[] groupName) {
        super(Groups.GROUPS);

        setId(id);
        setOwnerUserId(ownerUserId);
        setGroupName(groupName);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised GroupsRecord
     */
    public GroupsRecord(com.xnelo.filearch.jooq.tables.pojos.Groups value) {
        super(Groups.GROUPS);

        if (value != null) {
            setId(value.getId());
            setOwnerUserId(value.getOwnerUserId());
            setGroupName(value.getGroupName());
            resetTouchedOnNotNull();
        }
    }
}
