/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.records;


import com.xnelo.filearch.jooq.tables.GroupMemberPermissions;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupMemberPermissionsRecord extends TableRecordImpl<GroupMemberPermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>FILEARCH.group_member_permissions.user_id</code>.
     */
    public GroupMemberPermissionsRecord setUserId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_member_permissions.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>FILEARCH.group_member_permissions.group_id</code>.
     */
    public GroupMemberPermissionsRecord setGroupId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_member_permissions.group_id</code>.
     */
    public Long getGroupId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>FILEARCH.group_member_permissions.permission_granted</code>.
     */
    public GroupMemberPermissionsRecord setPermissionGranted(Short value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>FILEARCH.group_member_permissions.permission_granted</code>.
     */
    public Short getPermissionGranted() {
        return (Short) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupMemberPermissionsRecord
     */
    public GroupMemberPermissionsRecord() {
        super(GroupMemberPermissions.GROUP_MEMBER_PERMISSIONS);
    }

    /**
     * Create a detached, initialised GroupMemberPermissionsRecord
     */
    public GroupMemberPermissionsRecord(Long userId, Long groupId, Short permissionGranted) {
        super(GroupMemberPermissions.GROUP_MEMBER_PERMISSIONS);

        setUserId(userId);
        setGroupId(groupId);
        setPermissionGranted(permissionGranted);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised GroupMemberPermissionsRecord
     */
    public GroupMemberPermissionsRecord(com.xnelo.filearch.jooq.tables.pojos.GroupMemberPermissions value) {
        super(GroupMemberPermissions.GROUP_MEMBER_PERMISSIONS);

        if (value != null) {
            setUserId(value.getUserId());
            setGroupId(value.getGroupId());
            setPermissionGranted(value.getPermissionGranted());
            resetTouchedOnNotNull();
        }
    }
}
