/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.records;


import com.xnelo.filearch.jooq.tables.GroupItems;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupItemsRecord extends TableRecordImpl<GroupItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>FILEARCH.group_items.item_id</code>.
     */
    public GroupItemsRecord setItemId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_items.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>FILEARCH.group_items.item_type</code>.
     */
    public GroupItemsRecord setItemType(Short value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_items.item_type</code>.
     */
    public Short getItemType() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>FILEARCH.group_items.group_id</code>.
     */
    public GroupItemsRecord setGroupId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_items.group_id</code>.
     */
    public Long getGroupId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupItemsRecord
     */
    public GroupItemsRecord() {
        super(GroupItems.GROUP_ITEMS);
    }

    /**
     * Create a detached, initialised GroupItemsRecord
     */
    public GroupItemsRecord(Long itemId, Short itemType, Long groupId) {
        super(GroupItems.GROUP_ITEMS);

        setItemId(itemId);
        setItemType(itemType);
        setGroupId(groupId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised GroupItemsRecord
     */
    public GroupItemsRecord(com.xnelo.filearch.jooq.tables.pojos.GroupItems value) {
        super(GroupItems.GROUP_ITEMS);

        if (value != null) {
            setItemId(value.getItemId());
            setItemType(value.getItemType());
            setGroupId(value.getGroupId());
            resetTouchedOnNotNull();
        }
    }
}
