/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.records;


import com.xnelo.filearch.jooq.tables.GroupItemTags;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupItemTagsRecord extends TableRecordImpl<GroupItemTagsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>FILEARCH.group_item_tags.item_id</code>.
     */
    public GroupItemTagsRecord setItemId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_item_tags.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>FILEARCH.group_item_tags.item_type</code>.
     */
    public GroupItemTagsRecord setItemType(Short value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_item_tags.item_type</code>.
     */
    public Short getItemType() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>FILEARCH.group_item_tags.group_id</code>.
     */
    public GroupItemTagsRecord setGroupId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_item_tags.group_id</code>.
     */
    public Long getGroupId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>FILEARCH.group_item_tags.tag_id</code>.
     */
    public GroupItemTagsRecord setTagId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.group_item_tags.tag_id</code>.
     */
    public Long getTagId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupItemTagsRecord
     */
    public GroupItemTagsRecord() {
        super(GroupItemTags.GROUP_ITEM_TAGS);
    }

    /**
     * Create a detached, initialised GroupItemTagsRecord
     */
    public GroupItemTagsRecord(Long itemId, Short itemType, Long groupId, Long tagId) {
        super(GroupItemTags.GROUP_ITEM_TAGS);

        setItemId(itemId);
        setItemType(itemType);
        setGroupId(groupId);
        setTagId(tagId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised GroupItemTagsRecord
     */
    public GroupItemTagsRecord(com.xnelo.filearch.jooq.tables.pojos.GroupItemTags value) {
        super(GroupItemTags.GROUP_ITEM_TAGS);

        if (value != null) {
            setItemId(value.getItemId());
            setItemType(value.getItemType());
            setGroupId(value.getGroupId());
            setTagId(value.getTagId());
            resetTouchedOnNotNull();
        }
    }
}
