/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.records;


import com.xnelo.filearch.jooq.tables.SharedTags;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SharedTagsRecord extends TableRecordImpl<SharedTagsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>FILEARCH.shared_tags.tag_id</code>.
     */
    public SharedTagsRecord setTagId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.shared_tags.tag_id</code>.
     */
    public Long getTagId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>FILEARCH.shared_tags.group_id</code>.
     */
    public SharedTagsRecord setGroupId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.shared_tags.group_id</code>.
     */
    public Long getGroupId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SharedTagsRecord
     */
    public SharedTagsRecord() {
        super(SharedTags.SHARED_TAGS);
    }

    /**
     * Create a detached, initialised SharedTagsRecord
     */
    public SharedTagsRecord(Long tagId, Long groupId) {
        super(SharedTags.SHARED_TAGS);

        setTagId(tagId);
        setGroupId(groupId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised SharedTagsRecord
     */
    public SharedTagsRecord(com.xnelo.filearch.jooq.tables.pojos.SharedTags value) {
        super(SharedTags.SHARED_TAGS);

        if (value != null) {
            setTagId(value.getTagId());
            setGroupId(value.getGroupId());
            resetTouchedOnNotNull();
        }
    }
}
