/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.records;


import com.xnelo.filearch.jooq.tables.Tags;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TagsRecord extends UpdatableRecordImpl<TagsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>FILEARCH.tags.id</code>.
     */
    public TagsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.tags.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>FILEARCH.tags.owner_user_id</code>.
     */
    public TagsRecord setOwnerUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.tags.owner_user_id</code>.
     */
    public Long getOwnerUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>FILEARCH.tags.tag_name</code>.
     */
    public TagsRecord setTagName(byte[] value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.tags.tag_name</code>.
     */
    public byte[] getTagName() {
        return (byte[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagsRecord
     */
    public TagsRecord() {
        super(Tags.TAGS);
    }

    /**
     * Create a detached, initialised TagsRecord
     */
    public TagsRecord(Long id, Long ownerUserId, byte[] tagName) {
        super(Tags.TAGS);

        setId(id);
        setOwnerUserId(ownerUserId);
        setTagName(tagName);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised TagsRecord
     */
    public TagsRecord(com.xnelo.filearch.jooq.tables.pojos.Tags value) {
        super(Tags.TAGS);

        if (value != null) {
            setId(value.getId());
            setOwnerUserId(value.getOwnerUserId());
            setTagName(value.getTagName());
            resetTouchedOnNotNull();
        }
    }
}
