/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.records;

import com.xnelo.filearch.jooq.tables.TestTable;
import org.jooq.impl.TableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TestTableRecord extends TableRecordImpl<TestTableRecord> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>FILEARCH.test_table.id</code>. */
  public TestTableRecord setId(Integer value) {
    set(0, value);
    return this;
  }

  /** Getter for <code>FILEARCH.test_table.id</code>. */
  public Integer getId() {
    return (Integer) get(0);
  }

  /** Setter for <code>FILEARCH.test_table.name</code>. */
  public TestTableRecord setName(String value) {
    set(1, value);
    return this;
  }

  /** Getter for <code>FILEARCH.test_table.name</code>. */
  public String getName() {
    return (String) get(1);
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached TestTableRecord */
  public TestTableRecord() {
    super(TestTable.TEST_TABLE);
  }

  /** Create a detached, initialised TestTableRecord */
  public TestTableRecord(Integer id, String name) {
    super(TestTable.TEST_TABLE);

    setId(id);
    setName(name);
    resetTouchedOnNotNull();
  }

  /** Create a detached, initialised TestTableRecord */
  public TestTableRecord(com.xnelo.filearch.jooq.tables.pojos.TestTable value) {
    super(TestTable.TEST_TABLE);

    if (value != null) {
      setId(value.getId());
      setName(value.getName());
      resetTouchedOnNotNull();
    }
  }
}
