/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.records;

import com.xnelo.filearch.jooq.tables.Users;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>FILEARCH.users.id</code>. */
  public UsersRecord setId(Long value) {
    set(0, value);
    return this;
  }

  /** Getter for <code>FILEARCH.users.id</code>. */
  public Long getId() {
    return (Long) get(0);
  }

  /** Setter for <code>FILEARCH.users.username</code>. */
  public UsersRecord setUsername(byte[] value) {
    set(1, value);
    return this;
  }

  /** Getter for <code>FILEARCH.users.username</code>. */
  public byte[] getUsername() {
    return (byte[]) get(1);
  }

  /** Setter for <code>FILEARCH.users.first_name</code>. */
  public UsersRecord setFirstName(byte[] value) {
    set(2, value);
    return this;
  }

  /** Getter for <code>FILEARCH.users.first_name</code>. */
  public byte[] getFirstName() {
    return (byte[]) get(2);
  }

  /** Setter for <code>FILEARCH.users.last_name</code>. */
  public UsersRecord setLastName(byte[] value) {
    set(3, value);
    return this;
  }

  /** Getter for <code>FILEARCH.users.last_name</code>. */
  public byte[] getLastName() {
    return (byte[]) get(3);
  }

  /** Setter for <code>FILEARCH.users.email</code>. */
  public UsersRecord setEmail(byte[] value) {
    set(4, value);
    return this;
  }

  /** Getter for <code>FILEARCH.users.email</code>. */
  public byte[] getEmail() {
    return (byte[]) get(4);
  }

  /** Setter for <code>FILEARCH.users.external_id</code>. */
  public UsersRecord setExternalId(String value) {
    set(5, value);
    return this;
  }

  /** Getter for <code>FILEARCH.users.external_id</code>. */
  public String getExternalId() {
    return (String) get(5);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached UsersRecord */
  public UsersRecord() {
    super(Users.USERS);
  }

  /** Create a detached, initialised UsersRecord */
  public UsersRecord(
      Long id,
      byte[] username,
      byte[] firstName,
      byte[] lastName,
      byte[] email,
      String externalId) {
    super(Users.USERS);

    setId(id);
    setUsername(username);
    setFirstName(firstName);
    setLastName(lastName);
    setEmail(email);
    setExternalId(externalId);
    resetTouchedOnNotNull();
  }

  /** Create a detached, initialised UsersRecord */
  public UsersRecord(com.xnelo.filearch.jooq.tables.pojos.Users value) {
    super(Users.USERS);

    if (value != null) {
      setId(value.getId());
      setUsername(value.getUsername());
      setFirstName(value.getFirstName());
      setLastName(value.getLastName());
      setEmail(value.getEmail());
      setExternalId(value.getExternalId());
      resetTouchedOnNotNull();
    }
  }
}
