/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.records;


import com.xnelo.filearch.jooq.tables.Users;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>FILEARCH.users.id</code>.
     */
    public UsersRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>FILEARCH.users.external_id</code>.
     */
    public UsersRecord setExternalId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>FILEARCH.users.external_id</code>.
     */
    public String getExternalId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Integer id, String externalId) {
        super(Users.USERS);

        setId(id);
        setExternalId(externalId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(com.xnelo.filearch.jooq.tables.pojos.Users value) {
        super(Users.USERS);

        if (value != null) {
            setId(value.getId());
            setExternalId(value.getExternalId());
            resetTouchedOnNotNull();
        }
    }
}
