/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Artifacts implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long ownerUserId;
    private final Long storedFilesId;
    private final String storageKey;
    private final String mimeType;

    public Artifacts(Artifacts value) {
        this.id = value.id;
        this.ownerUserId = value.ownerUserId;
        this.storedFilesId = value.storedFilesId;
        this.storageKey = value.storageKey;
        this.mimeType = value.mimeType;
    }

    public Artifacts(
        Long id,
        Long ownerUserId,
        Long storedFilesId,
        String storageKey,
        String mimeType
    ) {
        this.id = id;
        this.ownerUserId = ownerUserId;
        this.storedFilesId = storedFilesId;
        this.storageKey = storageKey;
        this.mimeType = mimeType;
    }

    /**
     * Getter for <code>FILEARCH.artifacts.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>FILEARCH.artifacts.owner_user_id</code>.
     */
    public Long getOwnerUserId() {
        return this.ownerUserId;
    }

    /**
     * Getter for <code>FILEARCH.artifacts.stored_files_id</code>.
     */
    public Long getStoredFilesId() {
        return this.storedFilesId;
    }

    /**
     * Getter for <code>FILEARCH.artifacts.storage_key</code>.
     */
    public String getStorageKey() {
        return this.storageKey;
    }

    /**
     * Getter for <code>FILEARCH.artifacts.mime_type</code>.
     */
    public String getMimeType() {
        return this.mimeType;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Artifacts other = (Artifacts) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.ownerUserId == null) {
            if (other.ownerUserId != null)
                return false;
        }
        else if (!this.ownerUserId.equals(other.ownerUserId))
            return false;
        if (this.storedFilesId == null) {
            if (other.storedFilesId != null)
                return false;
        }
        else if (!this.storedFilesId.equals(other.storedFilesId))
            return false;
        if (this.storageKey == null) {
            if (other.storageKey != null)
                return false;
        }
        else if (!this.storageKey.equals(other.storageKey))
            return false;
        if (this.mimeType == null) {
            if (other.mimeType != null)
                return false;
        }
        else if (!this.mimeType.equals(other.mimeType))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.ownerUserId == null) ? 0 : this.ownerUserId.hashCode());
        result = prime * result + ((this.storedFilesId == null) ? 0 : this.storedFilesId.hashCode());
        result = prime * result + ((this.storageKey == null) ? 0 : this.storageKey.hashCode());
        result = prime * result + ((this.mimeType == null) ? 0 : this.mimeType.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Artifacts (");

        sb.append(id);
        sb.append(", ").append(ownerUserId);
        sb.append(", ").append(storedFilesId);
        sb.append(", ").append(storageKey);
        sb.append(", ").append(mimeType);

        sb.append(")");
        return sb.toString();
    }
}
