/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FileTags implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long fileId;
    private final Long tagId;

    public FileTags(FileTags value) {
        this.fileId = value.fileId;
        this.tagId = value.tagId;
    }

    public FileTags(
        Long fileId,
        Long tagId
    ) {
        this.fileId = fileId;
        this.tagId = tagId;
    }

    /**
     * Getter for <code>FILEARCH.file_tags.file_id</code>.
     */
    public Long getFileId() {
        return this.fileId;
    }

    /**
     * Getter for <code>FILEARCH.file_tags.tag_id</code>.
     */
    public Long getTagId() {
        return this.tagId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FileTags other = (FileTags) obj;
        if (this.fileId == null) {
            if (other.fileId != null)
                return false;
        }
        else if (!this.fileId.equals(other.fileId))
            return false;
        if (this.tagId == null) {
            if (other.tagId != null)
                return false;
        }
        else if (!this.tagId.equals(other.tagId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.fileId == null) ? 0 : this.fileId.hashCode());
        result = prime * result + ((this.tagId == null) ? 0 : this.tagId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FileTags (");

        sb.append(fileId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }
}
