/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupMemberPermissions implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long userId;
    private final Long groupId;
    private final Short permissionGranted;

    public GroupMemberPermissions(GroupMemberPermissions value) {
        this.userId = value.userId;
        this.groupId = value.groupId;
        this.permissionGranted = value.permissionGranted;
    }

    public GroupMemberPermissions(
        Long userId,
        Long groupId,
        Short permissionGranted
    ) {
        this.userId = userId;
        this.groupId = groupId;
        this.permissionGranted = permissionGranted;
    }

    /**
     * Getter for <code>FILEARCH.group_member_permissions.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>FILEARCH.group_member_permissions.group_id</code>.
     */
    public Long getGroupId() {
        return this.groupId;
    }

    /**
     * Getter for
     * <code>FILEARCH.group_member_permissions.permission_granted</code>.
     */
    public Short getPermissionGranted() {
        return this.permissionGranted;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GroupMemberPermissions other = (GroupMemberPermissions) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.groupId == null) {
            if (other.groupId != null)
                return false;
        }
        else if (!this.groupId.equals(other.groupId))
            return false;
        if (this.permissionGranted == null) {
            if (other.permissionGranted != null)
                return false;
        }
        else if (!this.permissionGranted.equals(other.permissionGranted))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.groupId == null) ? 0 : this.groupId.hashCode());
        result = prime * result + ((this.permissionGranted == null) ? 0 : this.permissionGranted.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GroupMemberPermissions (");

        sb.append(userId);
        sb.append(", ").append(groupId);
        sb.append(", ").append(permissionGranted);

        sb.append(")");
        return sb.toString();
    }
}
