/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupMembers implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long userId;
    private final Long groupId;
    private final Boolean accepted;

    public GroupMembers(GroupMembers value) {
        this.userId = value.userId;
        this.groupId = value.groupId;
        this.accepted = value.accepted;
    }

    public GroupMembers(
        Long userId,
        Long groupId,
        Boolean accepted
    ) {
        this.userId = userId;
        this.groupId = groupId;
        this.accepted = accepted;
    }

    /**
     * Getter for <code>FILEARCH.group_members.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>FILEARCH.group_members.group_id</code>.
     */
    public Long getGroupId() {
        return this.groupId;
    }

    /**
     * Getter for <code>FILEARCH.group_members.accepted</code>.
     */
    public Boolean getAccepted() {
        return this.accepted;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GroupMembers other = (GroupMembers) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.groupId == null) {
            if (other.groupId != null)
                return false;
        }
        else if (!this.groupId.equals(other.groupId))
            return false;
        if (this.accepted == null) {
            if (other.accepted != null)
                return false;
        }
        else if (!this.accepted.equals(other.accepted))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.groupId == null) ? 0 : this.groupId.hashCode());
        result = prime * result + ((this.accepted == null) ? 0 : this.accepted.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GroupMembers (");

        sb.append(userId);
        sb.append(", ").append(groupId);
        sb.append(", ").append(accepted);

        sb.append(")");
        return sb.toString();
    }
}
