/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupItems implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long itemId;
    private final Short itemType;
    private final Long groupId;

    public GroupItems(GroupItems value) {
        this.itemId = value.itemId;
        this.itemType = value.itemType;
        this.groupId = value.groupId;
    }

    public GroupItems(
        Long itemId,
        Short itemType,
        Long groupId
    ) {
        this.itemId = itemId;
        this.itemType = itemType;
        this.groupId = groupId;
    }

    /**
     * Getter for <code>FILEARCH.group_items.item_id</code>.
     */
    public Long getItemId() {
        return this.itemId;
    }

    /**
     * Getter for <code>FILEARCH.group_items.item_type</code>.
     */
    public Short getItemType() {
        return this.itemType;
    }

    /**
     * Getter for <code>FILEARCH.group_items.group_id</code>.
     */
    public Long getGroupId() {
        return this.groupId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GroupItems other = (GroupItems) obj;
        if (this.itemId == null) {
            if (other.itemId != null)
                return false;
        }
        else if (!this.itemId.equals(other.itemId))
            return false;
        if (this.itemType == null) {
            if (other.itemType != null)
                return false;
        }
        else if (!this.itemType.equals(other.itemType))
            return false;
        if (this.groupId == null) {
            if (other.groupId != null)
                return false;
        }
        else if (!this.groupId.equals(other.groupId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.itemId == null) ? 0 : this.itemId.hashCode());
        result = prime * result + ((this.itemType == null) ? 0 : this.itemType.hashCode());
        result = prime * result + ((this.groupId == null) ? 0 : this.groupId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GroupItems (");

        sb.append(itemId);
        sb.append(", ").append(itemType);
        sb.append(", ").append(groupId);

        sb.append(")");
        return sb.toString();
    }
}
