/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupAuditLog implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long groupId;
    private final Long userId;
    private final OffsetDateTime modifiedAt;
    private final Short modification;
    private final JSONB preOpData;
    private final JSONB postOpData;

    public GroupAuditLog(GroupAuditLog value) {
        this.id = value.id;
        this.groupId = value.groupId;
        this.userId = value.userId;
        this.modifiedAt = value.modifiedAt;
        this.modification = value.modification;
        this.preOpData = value.preOpData;
        this.postOpData = value.postOpData;
    }

    public GroupAuditLog(
        Long id,
        Long groupId,
        Long userId,
        OffsetDateTime modifiedAt,
        Short modification,
        JSONB preOpData,
        JSONB postOpData
    ) {
        this.id = id;
        this.groupId = groupId;
        this.userId = userId;
        this.modifiedAt = modifiedAt;
        this.modification = modification;
        this.preOpData = preOpData;
        this.postOpData = postOpData;
    }

    /**
     * Getter for <code>FILEARCH.group_audit_log.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>FILEARCH.group_audit_log.group_id</code>.
     */
    public Long getGroupId() {
        return this.groupId;
    }

    /**
     * Getter for <code>FILEARCH.group_audit_log.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>FILEARCH.group_audit_log.modified_at</code>.
     */
    public OffsetDateTime getModifiedAt() {
        return this.modifiedAt;
    }

    /**
     * Getter for <code>FILEARCH.group_audit_log.modification</code>.
     */
    public Short getModification() {
        return this.modification;
    }

    /**
     * Getter for <code>FILEARCH.group_audit_log.pre_op_data</code>.
     */
    public JSONB getPreOpData() {
        return this.preOpData;
    }

    /**
     * Getter for <code>FILEARCH.group_audit_log.post_op_data</code>.
     */
    public JSONB getPostOpData() {
        return this.postOpData;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GroupAuditLog other = (GroupAuditLog) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.groupId == null) {
            if (other.groupId != null)
                return false;
        }
        else if (!this.groupId.equals(other.groupId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.modifiedAt == null) {
            if (other.modifiedAt != null)
                return false;
        }
        else if (!this.modifiedAt.equals(other.modifiedAt))
            return false;
        if (this.modification == null) {
            if (other.modification != null)
                return false;
        }
        else if (!this.modification.equals(other.modification))
            return false;
        if (this.preOpData == null) {
            if (other.preOpData != null)
                return false;
        }
        else if (!this.preOpData.equals(other.preOpData))
            return false;
        if (this.postOpData == null) {
            if (other.postOpData != null)
                return false;
        }
        else if (!this.postOpData.equals(other.postOpData))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.groupId == null) ? 0 : this.groupId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.modifiedAt == null) ? 0 : this.modifiedAt.hashCode());
        result = prime * result + ((this.modification == null) ? 0 : this.modification.hashCode());
        result = prime * result + ((this.preOpData == null) ? 0 : this.preOpData.hashCode());
        result = prime * result + ((this.postOpData == null) ? 0 : this.postOpData.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GroupAuditLog (");

        sb.append(id);
        sb.append(", ").append(groupId);
        sb.append(", ").append(userId);
        sb.append(", ").append(modifiedAt);
        sb.append(", ").append(modification);
        sb.append(", ").append(preOpData);
        sb.append(", ").append(postOpData);

        sb.append(")");
        return sb.toString();
    }
}
