/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Groups implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long ownerUserId;
    private final byte[] groupName;

    public Groups(Groups value) {
        this.id = value.id;
        this.ownerUserId = value.ownerUserId;
        this.groupName = value.groupName;
    }

    public Groups(
        Long id,
        Long ownerUserId,
        byte[] groupName
    ) {
        this.id = id;
        this.ownerUserId = ownerUserId;
        this.groupName = groupName;
    }

    /**
     * Getter for <code>FILEARCH.groups.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>FILEARCH.groups.owner_user_id</code>.
     */
    public Long getOwnerUserId() {
        return this.ownerUserId;
    }

    /**
     * Getter for <code>FILEARCH.groups.group_name</code>.
     */
    public byte[] getGroupName() {
        return this.groupName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Groups other = (Groups) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.ownerUserId == null) {
            if (other.ownerUserId != null)
                return false;
        }
        else if (!this.ownerUserId.equals(other.ownerUserId))
            return false;
        if (this.groupName == null) {
            if (other.groupName != null)
                return false;
        }
        else if (!Arrays.equals(this.groupName, other.groupName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.ownerUserId == null) ? 0 : this.ownerUserId.hashCode());
        result = prime * result + ((this.groupName == null) ? 0 : Arrays.hashCode(this.groupName));
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Groups (");

        sb.append(id);
        sb.append(", ").append(ownerUserId);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
