/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.pojos;

import java.io.Serializable;
import java.util.Arrays;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Users implements Serializable {

  private static final long serialVersionUID = 1L;

  private final Long id;
  private final byte[] username;
  private final byte[] firstName;
  private final byte[] lastName;
  private final byte[] email;
  private final String externalId;

  public Users(Users value) {
    this.id = value.id;
    this.username = value.username;
    this.firstName = value.firstName;
    this.lastName = value.lastName;
    this.email = value.email;
    this.externalId = value.externalId;
  }

  public Users(
      Long id,
      byte[] username,
      byte[] firstName,
      byte[] lastName,
      byte[] email,
      String externalId) {
    this.id = id;
    this.username = username;
    this.firstName = firstName;
    this.lastName = lastName;
    this.email = email;
    this.externalId = externalId;
  }

  /** Getter for <code>FILEARCH.users.id</code>. */
  public Long getId() {
    return this.id;
  }

  /** Getter for <code>FILEARCH.users.username</code>. */
  public byte[] getUsername() {
    return this.username;
  }

  /** Getter for <code>FILEARCH.users.first_name</code>. */
  public byte[] getFirstName() {
    return this.firstName;
  }

  /** Getter for <code>FILEARCH.users.last_name</code>. */
  public byte[] getLastName() {
    return this.lastName;
  }

  /** Getter for <code>FILEARCH.users.email</code>. */
  public byte[] getEmail() {
    return this.email;
  }

  /** Getter for <code>FILEARCH.users.external_id</code>. */
  public String getExternalId() {
    return this.externalId;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    final Users other = (Users) obj;
    if (this.id == null) {
      if (other.id != null) return false;
    } else if (!this.id.equals(other.id)) return false;
    if (this.username == null) {
      if (other.username != null) return false;
    } else if (!Arrays.equals(this.username, other.username)) return false;
    if (this.firstName == null) {
      if (other.firstName != null) return false;
    } else if (!Arrays.equals(this.firstName, other.firstName)) return false;
    if (this.lastName == null) {
      if (other.lastName != null) return false;
    } else if (!Arrays.equals(this.lastName, other.lastName)) return false;
    if (this.email == null) {
      if (other.email != null) return false;
    } else if (!Arrays.equals(this.email, other.email)) return false;
    if (this.externalId == null) {
      if (other.externalId != null) return false;
    } else if (!this.externalId.equals(other.externalId)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
    result = prime * result + ((this.username == null) ? 0 : Arrays.hashCode(this.username));
    result = prime * result + ((this.firstName == null) ? 0 : Arrays.hashCode(this.firstName));
    result = prime * result + ((this.lastName == null) ? 0 : Arrays.hashCode(this.lastName));
    result = prime * result + ((this.email == null) ? 0 : Arrays.hashCode(this.email));
    result = prime * result + ((this.externalId == null) ? 0 : this.externalId.hashCode());
    return result;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Users (");

    sb.append(id);
    sb.append(", ").append("[binary...]");
    sb.append(", ").append("[binary...]");
    sb.append(", ").append("[binary...]");
    sb.append(", ").append("[binary...]");
    sb.append(", ").append(externalId);

    sb.append(")");
    return sb.toString();
  }
}
