/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String externalId;

    public Users(Users value) {
        this.id = value.id;
        this.externalId = value.externalId;
    }

    public Users(
        Integer id,
        String externalId
    ) {
        this.id = id;
        this.externalId = externalId;
    }

    /**
     * Getter for <code>FILEARCH.users.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>FILEARCH.users.external_id</code>.
     */
    public String getExternalId() {
        return this.externalId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Users other = (Users) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.externalId == null) {
            if (other.externalId != null)
                return false;
        }
        else if (!this.externalId.equals(other.externalId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.externalId == null) ? 0 : this.externalId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(externalId);

        sb.append(")");
        return sb.toString();
    }
}
