/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables.pojos;

import java.io.Serializable;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Users implements Serializable {

  private static final long serialVersionUID = 1L;

  private final Integer id;
  private final String username;
  private final String firstName;
  private final String lastName;
  private final String email;
  private final String externalId;

  public Users(Users value) {
    this.id = value.id;
    this.username = value.username;
    this.firstName = value.firstName;
    this.lastName = value.lastName;
    this.email = value.email;
    this.externalId = value.externalId;
  }

  public Users(
      Integer id,
      String username,
      String firstName,
      String lastName,
      String email,
      String externalId) {
    this.id = id;
    this.username = username;
    this.firstName = firstName;
    this.lastName = lastName;
    this.email = email;
    this.externalId = externalId;
  }

  /** Getter for <code>FILEARCH.users.id</code>. */
  public Integer getId() {
    return this.id;
  }

  /** Getter for <code>FILEARCH.users.username</code>. */
  public String getUsername() {
    return this.username;
  }

  /** Getter for <code>FILEARCH.users.first_name</code>. */
  public String getFirstName() {
    return this.firstName;
  }

  /** Getter for <code>FILEARCH.users.last_name</code>. */
  public String getLastName() {
    return this.lastName;
  }

  /** Getter for <code>FILEARCH.users.email</code>. */
  public String getEmail() {
    return this.email;
  }

  /** Getter for <code>FILEARCH.users.external_id</code>. */
  public String getExternalId() {
    return this.externalId;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    final Users other = (Users) obj;
    if (this.id == null) {
      if (other.id != null) return false;
    } else if (!this.id.equals(other.id)) return false;
    if (this.username == null) {
      if (other.username != null) return false;
    } else if (!this.username.equals(other.username)) return false;
    if (this.firstName == null) {
      if (other.firstName != null) return false;
    } else if (!this.firstName.equals(other.firstName)) return false;
    if (this.lastName == null) {
      if (other.lastName != null) return false;
    } else if (!this.lastName.equals(other.lastName)) return false;
    if (this.email == null) {
      if (other.email != null) return false;
    } else if (!this.email.equals(other.email)) return false;
    if (this.externalId == null) {
      if (other.externalId != null) return false;
    } else if (!this.externalId.equals(other.externalId)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
    result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
    result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
    result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
    result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
    result = prime * result + ((this.externalId == null) ? 0 : this.externalId.hashCode());
    return result;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Users (");

    sb.append(id);
    sb.append(", ").append(username);
    sb.append(", ").append(firstName);
    sb.append(", ").append(lastName);
    sb.append(", ").append(email);
    sb.append(", ").append(externalId);

    sb.append(")");
    return sb.toString();
  }
}
