package com.xnelo.filearch.common.model;

public enum ActionType {
  CREATE,
  UPLOAD,
  UPDATE,
  GET,
  DELETE,
  DOWNLOAD,
  ASSIGN,
  UNASSIGN,
  SEARCH,
  ADD_USER_TO_GROUP,
  REMOVE_USER_FROM_GROUP,
  ACCEPT_GROUP_INVITE,
  ADD_ITEM_TO_GROUP,
  REMOVE_ITEM_FROM_GROUP,
  GET_GROUP_PERMISSIONS
}
