services:
  keycloakDB:
    image: postgres:17.4
    container_name: keycloakDB
    environment:
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER:-keycl0ak}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD:-keycl0akPW}
      POSTGRES_DB: keycloakDB
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data:delegated
    ports:
      - "5431:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN:-Admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      FILEARCH_DEV_USER_PWD: ${FILEARCH_DEV_USER_PWD:-password1}
      FILEARCH_RESTAPI_SECRET: ${FILEARCH_RESTAPI_SECRET:-restapisecret}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakDB:5432/keycloakDB
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER:-keycl0ak}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD:-keycl0akPW}
    ports:
      - "9991:8080"
    depends_on:
      - keycloakDB
    volumes:
      - ../data/filearch-realm-export.json:/opt/keycloak/data/import/quarkus-realm.json
    labels:
      quarkus-dev-service-keycloak: quarkus
    command: start-dev --import-realm