services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN:-Admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      FILEARCH_DEV_USER_PWD: ${FILEARCH_DEV_USER_PWD:-password1}
      FILEARCH_RESTAPI_SECRET: ${FILEARCH_RESTAPI_SECRET:-restapisecret}
    ports:
      - "9991:8080"
    volumes:
      - ../data/filearch-realm-export.json:/opt/keycloak/data/import/quarkus-realm.json
    labels:
      quarkus-dev-service-keycloak: quarkus
    command: start-dev --import-realm