plugins {
    id 'io.quarkus'
    id("org.kordamp.gradle.jandex") version "2.1.0"
    id 'jvm-test-suite'
    id 'java-test-fixtures'
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation("io.quarkus:quarkus-jdbc-postgresql")
    implementation "io.quarkus:quarkus-oidc"
    implementation("io.quarkus:quarkus-rest-jackson")
    implementation("org.flywaydb:flyway-database-postgresql")
    implementation "org.jooq:jooq:${JOOQ_VERSION}"
    implementation "org.mapstruct:mapstruct:${MAPSTRUCT_VERSION}"
    implementation project(":jooq")

    compileOnly "org.projectlombok:lombok:${LOMBOK_VERSION}"

    annotationProcessor "org.projectlombok:lombok:${LOMBOK_VERSION}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${MAPSTRUCT_VERSION}"

    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")

    testFixturesImplementation("io.quarkus:quarkus-test-common:3.2.11.Final")
    testFixturesImplementation("org.testcontainers:postgresql:1.21.4")
    testFixturesImplementation("org.flywaydb:flyway-core:11.4.0")
    testFixturesImplementation("org.eclipse.microprofile.jwt:microprofile-jwt-auth-api:2.1")
    testFixturesImplementation("org.jooq:jooq:${JOOQ_VERSION}")
    testFixturesImplementation(project(":jooq"))
    testFixturesImplementation('com.github.javafaker:javafaker:1.0.2') {
        exclude group: 'org.yaml', module: 'snakeyaml'
    }
}

compileJava {
    options.compilerArgs += [
            '-Amapstruct.unmappedTargetPolicy=ERROR',
            '-Amapstruct.verbose=true'
    ]
}

quarkusDependenciesBuild {
    dependsOn("jandex")
}

testing {
    // intellij IDE shows an error around suites.
    // This is correct verify through command line before changing.
    suites {
        test {
            useJUnitJupiter() // Explicitly declares the framework on the suite
        }
    }
}