/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables;


import com.xnelo.filearch.jooq.Filearch;
import com.xnelo.filearch.jooq.Keys;
import com.xnelo.filearch.jooq.tables.records.ArtifactsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Artifacts extends TableImpl<ArtifactsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>FILEARCH.artifacts</code>
     */
    public static final Artifacts ARTIFACTS = new Artifacts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ArtifactsRecord> getRecordType() {
        return ArtifactsRecord.class;
    }

    /**
     * The column <code>FILEARCH.artifacts.id</code>.
     */
    public final TableField<ArtifactsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>FILEARCH.artifacts.owner_user_id</code>.
     */
    public final TableField<ArtifactsRecord, Long> OWNER_USER_ID = createField(DSL.name("owner_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>FILEARCH.artifacts.stored_files_id</code>.
     */
    public final TableField<ArtifactsRecord, Long> STORED_FILES_ID = createField(DSL.name("stored_files_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>FILEARCH.artifacts.storage_key</code>.
     */
    public final TableField<ArtifactsRecord, String> STORAGE_KEY = createField(DSL.name("storage_key"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>FILEARCH.artifacts.mime_type</code>.
     */
    public final TableField<ArtifactsRecord, String> MIME_TYPE = createField(DSL.name("mime_type"), SQLDataType.VARCHAR(255), this, "");

    private Artifacts(Name alias, Table<ArtifactsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Artifacts(Name alias, Table<ArtifactsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>FILEARCH.artifacts</code> table reference
     */
    public Artifacts(String alias) {
        this(DSL.name(alias), ARTIFACTS);
    }

    /**
     * Create an aliased <code>FILEARCH.artifacts</code> table reference
     */
    public Artifacts(Name alias) {
        this(alias, ARTIFACTS);
    }

    /**
     * Create a <code>FILEARCH.artifacts</code> table reference
     */
    public Artifacts() {
        this(DSL.name("artifacts"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Filearch.FILEARCH;
    }

    @Override
    public Identity<ArtifactsRecord, Long> getIdentity() {
        return (Identity<ArtifactsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ArtifactsRecord> getPrimaryKey() {
        return Keys.ARTIFACTS_PKEY;
    }

    @Override
    public Artifacts as(String alias) {
        return new Artifacts(DSL.name(alias), this);
    }

    @Override
    public Artifacts as(Name alias) {
        return new Artifacts(alias, this);
    }

    @Override
    public Artifacts as(Table<?> alias) {
        return new Artifacts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Artifacts rename(String name) {
        return new Artifacts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Artifacts rename(Name name) {
        return new Artifacts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Artifacts rename(Table<?> name) {
        return new Artifacts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artifacts where(Condition condition) {
        return new Artifacts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artifacts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artifacts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artifacts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artifacts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artifacts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artifacts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Artifacts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artifacts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Artifacts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
