/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables;


import com.xnelo.filearch.jooq.Filearch;
import com.xnelo.filearch.jooq.Keys;
import com.xnelo.filearch.jooq.tables.records.FileTagsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FileTags extends TableImpl<FileTagsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>FILEARCH.file_tags</code>
     */
    public static final FileTags FILE_TAGS = new FileTags();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileTagsRecord> getRecordType() {
        return FileTagsRecord.class;
    }

    /**
     * The column <code>FILEARCH.file_tags.file_id</code>.
     */
    public final TableField<FileTagsRecord, Long> FILE_ID = createField(DSL.name("file_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>FILEARCH.file_tags.tag_id</code>.
     */
    public final TableField<FileTagsRecord, Long> TAG_ID = createField(DSL.name("tag_id"), SQLDataType.BIGINT, this, "");

    private FileTags(Name alias, Table<FileTagsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FileTags(Name alias, Table<FileTagsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>FILEARCH.file_tags</code> table reference
     */
    public FileTags(String alias) {
        this(DSL.name(alias), FILE_TAGS);
    }

    /**
     * Create an aliased <code>FILEARCH.file_tags</code> table reference
     */
    public FileTags(Name alias) {
        this(alias, FILE_TAGS);
    }

    /**
     * Create a <code>FILEARCH.file_tags</code> table reference
     */
    public FileTags() {
        this(DSL.name("file_tags"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Filearch.FILEARCH;
    }

    @Override
    public List<UniqueKey<FileTagsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_FILE_TAGGING);
    }

    @Override
    public FileTags as(String alias) {
        return new FileTags(DSL.name(alias), this);
    }

    @Override
    public FileTags as(Name alias) {
        return new FileTags(alias, this);
    }

    @Override
    public FileTags as(Table<?> alias) {
        return new FileTags(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FileTags rename(String name) {
        return new FileTags(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileTags rename(Name name) {
        return new FileTags(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileTags rename(Table<?> name) {
        return new FileTags(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileTags where(Condition condition) {
        return new FileTags(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileTags where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileTags where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileTags where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileTags where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileTags where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileTags where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileTags where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileTags whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileTags whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
