/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables;


import com.xnelo.filearch.jooq.Filearch;
import com.xnelo.filearch.jooq.tables.records.GroupMembersRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupMembers extends TableImpl<GroupMembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>FILEARCH.group_members</code>
     */
    public static final GroupMembers GROUP_MEMBERS = new GroupMembers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GroupMembersRecord> getRecordType() {
        return GroupMembersRecord.class;
    }

    /**
     * The column <code>FILEARCH.group_members.user_id</code>.
     */
    public final TableField<GroupMembersRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>FILEARCH.group_members.group_id</code>.
     */
    public final TableField<GroupMembersRecord, Long> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>FILEARCH.group_members.accepted</code>.
     */
    public final TableField<GroupMembersRecord, Boolean> ACCEPTED = createField(DSL.name("accepted"), SQLDataType.BOOLEAN, this, "");

    private GroupMembers(Name alias, Table<GroupMembersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GroupMembers(Name alias, Table<GroupMembersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>FILEARCH.group_members</code> table reference
     */
    public GroupMembers(String alias) {
        this(DSL.name(alias), GROUP_MEMBERS);
    }

    /**
     * Create an aliased <code>FILEARCH.group_members</code> table reference
     */
    public GroupMembers(Name alias) {
        this(alias, GROUP_MEMBERS);
    }

    /**
     * Create a <code>FILEARCH.group_members</code> table reference
     */
    public GroupMembers() {
        this(DSL.name("group_members"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Filearch.FILEARCH;
    }

    @Override
    public GroupMembers as(String alias) {
        return new GroupMembers(DSL.name(alias), this);
    }

    @Override
    public GroupMembers as(Name alias) {
        return new GroupMembers(alias, this);
    }

    @Override
    public GroupMembers as(Table<?> alias) {
        return new GroupMembers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupMembers rename(String name) {
        return new GroupMembers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupMembers rename(Name name) {
        return new GroupMembers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupMembers rename(Table<?> name) {
        return new GroupMembers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupMembers where(Condition condition) {
        return new GroupMembers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupMembers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupMembers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupMembers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupMembers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupMembers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupMembers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupMembers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupMembers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupMembers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
