/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables;


import com.xnelo.filearch.jooq.Filearch;
import com.xnelo.filearch.jooq.tables.records.GroupItemsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupItems extends TableImpl<GroupItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>FILEARCH.group_items</code>
     */
    public static final GroupItems GROUP_ITEMS = new GroupItems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GroupItemsRecord> getRecordType() {
        return GroupItemsRecord.class;
    }

    /**
     * The column <code>FILEARCH.group_items.item_id</code>.
     */
    public final TableField<GroupItemsRecord, Long> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>FILEARCH.group_items.item_type</code>.
     */
    public final TableField<GroupItemsRecord, Short> ITEM_TYPE = createField(DSL.name("item_type"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>FILEARCH.group_items.group_id</code>.
     */
    public final TableField<GroupItemsRecord, Long> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.BIGINT, this, "");

    private GroupItems(Name alias, Table<GroupItemsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GroupItems(Name alias, Table<GroupItemsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>FILEARCH.group_items</code> table reference
     */
    public GroupItems(String alias) {
        this(DSL.name(alias), GROUP_ITEMS);
    }

    /**
     * Create an aliased <code>FILEARCH.group_items</code> table reference
     */
    public GroupItems(Name alias) {
        this(alias, GROUP_ITEMS);
    }

    /**
     * Create a <code>FILEARCH.group_items</code> table reference
     */
    public GroupItems() {
        this(DSL.name("group_items"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Filearch.FILEARCH;
    }

    @Override
    public GroupItems as(String alias) {
        return new GroupItems(DSL.name(alias), this);
    }

    @Override
    public GroupItems as(Name alias) {
        return new GroupItems(alias, this);
    }

    @Override
    public GroupItems as(Table<?> alias) {
        return new GroupItems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupItems rename(String name) {
        return new GroupItems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupItems rename(Name name) {
        return new GroupItems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupItems rename(Table<?> name) {
        return new GroupItems(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupItems where(Condition condition) {
        return new GroupItems(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupItems where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupItems where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupItems where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupItems where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupItems where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupItems where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupItems where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupItems whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupItems whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
