/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables;


import com.xnelo.filearch.jooq.Filearch;
import com.xnelo.filearch.jooq.Keys;
import com.xnelo.filearch.jooq.tables.records.GroupAuditLogRecord;

import java.time.OffsetDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupAuditLog extends TableImpl<GroupAuditLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>FILEARCH.group_audit_log</code>
     */
    public static final GroupAuditLog GROUP_AUDIT_LOG = new GroupAuditLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GroupAuditLogRecord> getRecordType() {
        return GroupAuditLogRecord.class;
    }

    /**
     * The column <code>FILEARCH.group_audit_log.id</code>.
     */
    public final TableField<GroupAuditLogRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>FILEARCH.group_audit_log.group_id</code>.
     */
    public final TableField<GroupAuditLogRecord, Long> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>FILEARCH.group_audit_log.user_id</code>.
     */
    public final TableField<GroupAuditLogRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>FILEARCH.group_audit_log.modified_at</code>.
     */
    public final TableField<GroupAuditLogRecord, OffsetDateTime> MODIFIED_AT = createField(DSL.name("modified_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>FILEARCH.group_audit_log.modification</code>.
     */
    public final TableField<GroupAuditLogRecord, Short> MODIFICATION = createField(DSL.name("modification"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>FILEARCH.group_audit_log.pre_op_data</code>.
     */
    public final TableField<GroupAuditLogRecord, JSONB> PRE_OP_DATA = createField(DSL.name("pre_op_data"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>FILEARCH.group_audit_log.post_op_data</code>.
     */
    public final TableField<GroupAuditLogRecord, JSONB> POST_OP_DATA = createField(DSL.name("post_op_data"), SQLDataType.JSONB, this, "");

    private GroupAuditLog(Name alias, Table<GroupAuditLogRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GroupAuditLog(Name alias, Table<GroupAuditLogRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>FILEARCH.group_audit_log</code> table reference
     */
    public GroupAuditLog(String alias) {
        this(DSL.name(alias), GROUP_AUDIT_LOG);
    }

    /**
     * Create an aliased <code>FILEARCH.group_audit_log</code> table reference
     */
    public GroupAuditLog(Name alias) {
        this(alias, GROUP_AUDIT_LOG);
    }

    /**
     * Create a <code>FILEARCH.group_audit_log</code> table reference
     */
    public GroupAuditLog() {
        this(DSL.name("group_audit_log"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Filearch.FILEARCH;
    }

    @Override
    public Identity<GroupAuditLogRecord, Long> getIdentity() {
        return (Identity<GroupAuditLogRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GroupAuditLogRecord> getPrimaryKey() {
        return Keys.GROUP_AUDIT_LOG_PKEY;
    }

    @Override
    public GroupAuditLog as(String alias) {
        return new GroupAuditLog(DSL.name(alias), this);
    }

    @Override
    public GroupAuditLog as(Name alias) {
        return new GroupAuditLog(alias, this);
    }

    @Override
    public GroupAuditLog as(Table<?> alias) {
        return new GroupAuditLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupAuditLog rename(String name) {
        return new GroupAuditLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupAuditLog rename(Name name) {
        return new GroupAuditLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupAuditLog rename(Table<?> name) {
        return new GroupAuditLog(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupAuditLog where(Condition condition) {
        return new GroupAuditLog(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupAuditLog where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupAuditLog where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupAuditLog where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupAuditLog where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupAuditLog where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupAuditLog where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupAuditLog where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupAuditLog whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupAuditLog whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
