/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables;


import com.xnelo.filearch.jooq.Filearch;
import com.xnelo.filearch.jooq.tables.records.GroupItemTagsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupItemTags extends TableImpl<GroupItemTagsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>FILEARCH.group_item_tags</code>
     */
    public static final GroupItemTags GROUP_ITEM_TAGS = new GroupItemTags();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GroupItemTagsRecord> getRecordType() {
        return GroupItemTagsRecord.class;
    }

    /**
     * The column <code>FILEARCH.group_item_tags.item_id</code>.
     */
    public final TableField<GroupItemTagsRecord, Long> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>FILEARCH.group_item_tags.item_type</code>.
     */
    public final TableField<GroupItemTagsRecord, Short> ITEM_TYPE = createField(DSL.name("item_type"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>FILEARCH.group_item_tags.group_id</code>.
     */
    public final TableField<GroupItemTagsRecord, Long> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>FILEARCH.group_item_tags.tag_id</code>.
     */
    public final TableField<GroupItemTagsRecord, Long> TAG_ID = createField(DSL.name("tag_id"), SQLDataType.BIGINT, this, "");

    private GroupItemTags(Name alias, Table<GroupItemTagsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GroupItemTags(Name alias, Table<GroupItemTagsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>FILEARCH.group_item_tags</code> table reference
     */
    public GroupItemTags(String alias) {
        this(DSL.name(alias), GROUP_ITEM_TAGS);
    }

    /**
     * Create an aliased <code>FILEARCH.group_item_tags</code> table reference
     */
    public GroupItemTags(Name alias) {
        this(alias, GROUP_ITEM_TAGS);
    }

    /**
     * Create a <code>FILEARCH.group_item_tags</code> table reference
     */
    public GroupItemTags() {
        this(DSL.name("group_item_tags"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Filearch.FILEARCH;
    }

    @Override
    public GroupItemTags as(String alias) {
        return new GroupItemTags(DSL.name(alias), this);
    }

    @Override
    public GroupItemTags as(Name alias) {
        return new GroupItemTags(alias, this);
    }

    @Override
    public GroupItemTags as(Table<?> alias) {
        return new GroupItemTags(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupItemTags rename(String name) {
        return new GroupItemTags(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupItemTags rename(Name name) {
        return new GroupItemTags(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupItemTags rename(Table<?> name) {
        return new GroupItemTags(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupItemTags where(Condition condition) {
        return new GroupItemTags(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupItemTags where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupItemTags where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupItemTags where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupItemTags where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupItemTags where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupItemTags where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupItemTags where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupItemTags whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupItemTags whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
