/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables;


import com.xnelo.filearch.jooq.Filearch;
import com.xnelo.filearch.jooq.tables.records.GroupMemberPermissionsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupMemberPermissions extends TableImpl<GroupMemberPermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>FILEARCH.group_member_permissions</code>
     */
    public static final GroupMemberPermissions GROUP_MEMBER_PERMISSIONS = new GroupMemberPermissions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GroupMemberPermissionsRecord> getRecordType() {
        return GroupMemberPermissionsRecord.class;
    }

    /**
     * The column <code>FILEARCH.group_member_permissions.user_id</code>.
     */
    public final TableField<GroupMemberPermissionsRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>FILEARCH.group_member_permissions.group_id</code>.
     */
    public final TableField<GroupMemberPermissionsRecord, Long> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column
     * <code>FILEARCH.group_member_permissions.permission_granted</code>.
     */
    public final TableField<GroupMemberPermissionsRecord, Short> PERMISSION_GRANTED = createField(DSL.name("permission_granted"), SQLDataType.SMALLINT, this, "");

    private GroupMemberPermissions(Name alias, Table<GroupMemberPermissionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GroupMemberPermissions(Name alias, Table<GroupMemberPermissionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>FILEARCH.group_member_permissions</code> table
     * reference
     */
    public GroupMemberPermissions(String alias) {
        this(DSL.name(alias), GROUP_MEMBER_PERMISSIONS);
    }

    /**
     * Create an aliased <code>FILEARCH.group_member_permissions</code> table
     * reference
     */
    public GroupMemberPermissions(Name alias) {
        this(alias, GROUP_MEMBER_PERMISSIONS);
    }

    /**
     * Create a <code>FILEARCH.group_member_permissions</code> table reference
     */
    public GroupMemberPermissions() {
        this(DSL.name("group_member_permissions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Filearch.FILEARCH;
    }

    @Override
    public GroupMemberPermissions as(String alias) {
        return new GroupMemberPermissions(DSL.name(alias), this);
    }

    @Override
    public GroupMemberPermissions as(Name alias) {
        return new GroupMemberPermissions(alias, this);
    }

    @Override
    public GroupMemberPermissions as(Table<?> alias) {
        return new GroupMemberPermissions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupMemberPermissions rename(String name) {
        return new GroupMemberPermissions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupMemberPermissions rename(Name name) {
        return new GroupMemberPermissions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupMemberPermissions rename(Table<?> name) {
        return new GroupMemberPermissions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupMemberPermissions where(Condition condition) {
        return new GroupMemberPermissions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupMemberPermissions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupMemberPermissions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupMemberPermissions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupMemberPermissions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupMemberPermissions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupMemberPermissions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GroupMemberPermissions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupMemberPermissions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GroupMemberPermissions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
