/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.tables;


import com.xnelo.filearch.jooq.Filearch;
import com.xnelo.filearch.jooq.tables.records.SharedTagsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SharedTags extends TableImpl<SharedTagsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>FILEARCH.shared_tags</code>
     */
    public static final SharedTags SHARED_TAGS = new SharedTags();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SharedTagsRecord> getRecordType() {
        return SharedTagsRecord.class;
    }

    /**
     * The column <code>FILEARCH.shared_tags.tag_id</code>.
     */
    public final TableField<SharedTagsRecord, Long> TAG_ID = createField(DSL.name("tag_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>FILEARCH.shared_tags.group_id</code>.
     */
    public final TableField<SharedTagsRecord, Long> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.BIGINT, this, "");

    private SharedTags(Name alias, Table<SharedTagsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SharedTags(Name alias, Table<SharedTagsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>FILEARCH.shared_tags</code> table reference
     */
    public SharedTags(String alias) {
        this(DSL.name(alias), SHARED_TAGS);
    }

    /**
     * Create an aliased <code>FILEARCH.shared_tags</code> table reference
     */
    public SharedTags(Name alias) {
        this(alias, SHARED_TAGS);
    }

    /**
     * Create a <code>FILEARCH.shared_tags</code> table reference
     */
    public SharedTags() {
        this(DSL.name("shared_tags"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Filearch.FILEARCH;
    }

    @Override
    public SharedTags as(String alias) {
        return new SharedTags(DSL.name(alias), this);
    }

    @Override
    public SharedTags as(Name alias) {
        return new SharedTags(alias, this);
    }

    @Override
    public SharedTags as(Table<?> alias) {
        return new SharedTags(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SharedTags rename(String name) {
        return new SharedTags(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SharedTags rename(Name name) {
        return new SharedTags(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SharedTags rename(Table<?> name) {
        return new SharedTags(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SharedTags where(Condition condition) {
        return new SharedTags(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SharedTags where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SharedTags where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SharedTags where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SharedTags where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SharedTags where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SharedTags where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SharedTags where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SharedTags whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SharedTags whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
