/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq;


import com.xnelo.filearch.jooq.tables.Artifacts;
import com.xnelo.filearch.jooq.tables.FlywaySchemaHistory;
import com.xnelo.filearch.jooq.tables.Folders;
import com.xnelo.filearch.jooq.tables.StoredFiles;
import com.xnelo.filearch.jooq.tables.Users;
import com.xnelo.filearch.jooq.tables.records.ArtifactsRecord;
import com.xnelo.filearch.jooq.tables.records.FlywaySchemaHistoryRecord;
import com.xnelo.filearch.jooq.tables.records.FoldersRecord;
import com.xnelo.filearch.jooq.tables.records.StoredFilesRecord;
import com.xnelo.filearch.jooq.tables.records.UsersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * FILEARCH.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ArtifactsRecord> ARTIFACTS_PKEY = Internal.createUniqueKey(Artifacts.ARTIFACTS, DSL.name("artifacts_pkey"), new TableField[] { Artifacts.ARTIFACTS.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<FoldersRecord> FOLDERS_PKEY = Internal.createUniqueKey(Folders.FOLDERS, DSL.name("folders_pkey"), new TableField[] { Folders.FOLDERS.ID }, true);
    public static final UniqueKey<StoredFilesRecord> STORED_FILES_PKEY = Internal.createUniqueKey(StoredFiles.STORED_FILES, DSL.name("stored_files_pkey"), new TableField[] { StoredFiles.STORED_FILES.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
}
