/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq;

import com.xnelo.filearch.jooq.tables.FlywaySchemaHistory;
import com.xnelo.filearch.jooq.tables.StoredFiles;
import com.xnelo.filearch.jooq.tables.Users;

/** Convenience access to all tables in FILEARCH. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

  /** The table <code>FILEARCH.flyway_schema_history</code>. */
  public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY =
      FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

  /** The table <code>FILEARCH.stored_files</code>. */
  public static final StoredFiles STORED_FILES = StoredFiles.STORED_FILES;

  /** The table <code>FILEARCH.users</code>. */
  public static final Users USERS = Users.USERS;
}
