/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq;

import com.xnelo.filearch.jooq.tables.FlywaySchemaHistory;
import com.xnelo.filearch.jooq.tables.TestTable;

/** Convenience access to all tables in FILEARCH. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

  /** The table <code>FILEARCH.flyway_schema_history</code>. */
  public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY =
      FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

  /** The table <code>FILEARCH.test_table</code>. */
  public static final TestTable TEST_TABLE = TestTable.TEST_TABLE;
}
