/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.routines;

import com.xnelo.filearch.jooq.Filearch;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class GenSalt1 extends AbstractRoutine<String> {

  private static final long serialVersionUID = 1L;

  /** The parameter <code>FILEARCH.gen_salt.RETURN_VALUE</code>. */
  public static final Parameter<String> RETURN_VALUE =
      Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false);

  /** The parameter <code>FILEARCH.gen_salt._1</code>. */
  public static final Parameter<String> _1 =
      Internal.createParameter("_1", SQLDataType.CLOB, false, true);

  /** Create a new routine call instance */
  public GenSalt1() {
    super("gen_salt", Filearch.FILEARCH, DSL.comment(""), SQLDataType.CLOB);

    setReturnParameter(RETURN_VALUE);
    addInParameter(_1);
    setOverloaded(true);
  }

  /** Set the <code>_1</code> parameter IN value to the routine */
  public void set__1(String value) {
    setValue(_1, value);
  }

  /**
   * Set the <code>_1</code> parameter to the function to be used with a {@link org.jooq.Select}
   * statement
   */
  public GenSalt1 set__1(Field<String> field) {
    setField(_1, field);
    return this;
  }
}
