/*
 * This file is generated by jOOQ.
 */
package com.xnelo.filearch.jooq.routines;


import com.xnelo.filearch.jooq.Filearch;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgpSymDecryptNullOnErr extends AbstractRoutine<String> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter
     * <code>FILEARCH.pgp_sym_decrypt_null_on_err.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>FILEARCH.pgp_sym_decrypt_null_on_err.data</code>.
     */
    public static final Parameter<byte[]> DATA = Internal.createParameter("data", SQLDataType.BLOB, false, false);

    /**
     * The parameter <code>FILEARCH.pgp_sym_decrypt_null_on_err.psw</code>.
     */
    public static final Parameter<String> PSW = Internal.createParameter("psw", SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public PgpSymDecryptNullOnErr() {
        super("pgp_sym_decrypt_null_on_err", Filearch.FILEARCH, DSL.comment(""), SQLDataType.CLOB);

        setReturnParameter(RETURN_VALUE);
        addInParameter(DATA);
        addInParameter(PSW);
    }

    /**
     * Set the <code>data</code> parameter IN value to the routine
     */
    public void setData(byte[] value) {
        setValue(DATA, value);
    }

    /**
     * Set the <code>data</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public PgpSymDecryptNullOnErr setData(Field<byte[]> field) {
        setField(DATA, field);
        return this;
    }

    /**
     * Set the <code>psw</code> parameter IN value to the routine
     */
    public void setPsw(String value) {
        setValue(PSW, value);
    }

    /**
     * Set the <code>psw</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public PgpSymDecryptNullOnErr setPsw(Field<String> field) {
        setField(PSW, field);
        return this;
    }
}
